### PR TITLE
feat: Refactor integration tests 5-appinfra

### PR DESCRIPTION
**Pull request by amandakarina**
Combine app infra tests in one file, enable running in paralalel.

### CODE REVIEW

**Comment by apeabody** [comment]
retry

```
        	Error:      	Received unexpected error:
        	            	FatalError{Underlying: error while running command: exit status 1; 
        	            	Error: Error waiting to create Feature: Error waiting for Creating Feature: Error code 13, message: an internal error has occurred
        	            	
        	            	  with module.env.google_gke_hub_feature.poco_feature,
        	            	  on ../../modules/env_baseline/policy.tf line 17, in resource "google_gke_hub_feature" "poco_feature":
        	            	  17: resource "google_gke_hub_feature" "poco_feature" {
        	            	}
        	Test:       	TestFleetscope/production
```

**Comment by apeabody** [comment]
`FAIL: TestSourceCymbalBank/../../../6-appsource/cymbal-bank/ledger-ledgerwriter`

**Comment by amandakarina** [comment]
Build time:
From 1h 23m without Cloud build parallel steps to 1h 16min enabling parallel steps.

**Review by apeabody — APPROVED** [review]
Thanks @amandakarina! LGTM

**Pull request merged**
