### PR TITLE
feat(appfactory): refactor appfactory to support multiple apps and nested parallel tests

### PR DESCRIPTION
**Pull request by apeabody**
Fixes: #111, #129

- initial support for multiple apps (tests in parallel, nested tests in parallel)
- refactor from using single `cymbal-bank/frontend` app group baseline to one for each `cymbal-bank` component (e.g. frontend)
- refactor cymbal-bank to use `for_each` to greatly reduce duplicate code
- add missing backend config
- add schema for some complex variables (`envs`)

### CODE REVIEW

**Comment by apeabody** [comment]
Per #111 - I'll update to use the nested cymbal-bank with an appfactory for each "sub-app".

**Comment by apeabody** [comment]
another flake due to `Error: Provider produced inconsistent result after apply` on a service account creation

**Comment by apeabody** [comment]
```
Step #11 - "appfactory-apply": Error: Error creating service account: googleapi: Error 409: Service account tf-cb-userservice-i-r already exists within project projects/userservice-admin-4a5c.
Step #11 - "appfactory-apply": Details:
Step #11 - "appfactory-apply": [
Step #11 - "appfactory-apply":   {
Step #11 - "appfactory-apply":     "@type": "type.googleapis.com/google.rpc.ResourceInfo",
Step #11 - "appfactory-apply":     "resourceName": "projects/userservice-admin-4a5c/serviceAccounts/tf-cb-userservice-i-r@userservice-admin-4a5c.iam.gserviceaccount.com"
Step #11 - "appfactory-apply":   }
Step #11 - "appfactory-apply": ]
Step #11 - "appfactory-apply": , alreadyExists
```

**Comment by apeabody** [comment]
Released updated [project-factory v15.0.1](https://github.com/terraform-google-modules/terraform-google-project-factory/releases/tag/v15.0.1) to help with #115

`TestMultitenant/development 2024-05-17T19:46:41Z command.go:185: Downloading registry.terraform.io/terraform-google-modules/project-factory/google 15.0.1 for env.eab_cluster_project...`

**Review by amandakarina — APPROVED** [review]
LGTM

**Review by sleighton2022 — APPROVED** [review]

**Pull request merged**
