### PR TITLE
feat(appinfra): configurable envs

### PR DESCRIPTION
**Pull request by apeabody**
- Replace appinfra's hard coded prod/non-prod/dev environments with a configurable list

### CODE REVIEW

**Comment by apeabody** [comment]
```
        	Error:      	Received unexpected error:
        	            	FatalError{Underlying: error while running command: exit status 1; 
        	            	Error: Error waiting to create Feature: Error waiting for Creating Feature: Error code 13, message: an internal error has occurred
        	            	
        	            	  with module.env.google_gke_hub_feature.mcs,
        	            	  on ../../modules/env_baseline/mcg.tf line 34, in resource "google_gke_hub_feature" "mcs":
        	            	  34: resource "google_gke_hub_feature" "mcs" {
        	            	}
        	Test:       	TestFleetscope/production
```

**Comment by apeabody** [comment]
```
        	Error:      	Received unexpected error:
        	            	FatalError{Underlying: error while running command: exit status 1; 
        	            	Error: Error waiting to create Feature: Error waiting for Creating Feature: Error code 13, message: an internal error has occurred
        	            	
        	            	  with module.env.google_gke_hub_feature.acm_feature,
        	            	  on ../../modules/env_baseline/acm.tf line 44, in resource "google_gke_hub_feature" "acm_feature":
        	            	  44: resource "google_gke_hub_feature" "acm_feature" {
        	            	}
        	Test:       	TestFleetscope/development
```

**Comment by apeabody** [comment]
```
        	Error:      	Received unexpected error:
        	            	FatalError{Underlying: error while running command: exit status 1; 
        	            	Error: Error waiting to create Feature: Error waiting for Creating Feature: Error code 13, message: an internal error has occurred
        	            	
        	            	  with module.env.google_gke_hub_feature.mcs,
        	            	  on ../../modules/env_baseline/mcg.tf line 34, in resource "google_gke_hub_feature" "mcs":
        	            	  34: resource "google_gke_hub_feature" "mcs" {
        	            	}
        	Test:       	TestFleetscope/non-production
```

**Comment by apeabody** [comment]
```
        	Error:      	Received unexpected error:
        	            	FatalError{Underlying: error while running command: exit status 1; 
        	            	Error: Error waiting to create Feature: Error waiting for Creating Feature: Error code 13, message: an internal error has occurred
        	            	
        	            	  with module.env.google_gke_hub_feature.acm_feature,
        	            	  on ../../modules/env_baseline/acm.tf line 44, in resource "google_gke_hub_feature" "acm_feature":
        	            	  44: resource "google_gke_hub_feature" "acm_feature" {
        	            	}
        	Test:       	TestFleetscope/production
```

**Comment by apeabody** [comment]
```
Step #8 - "fleetscope-apply":         	Error:      	Received unexpected error:
Step #8 - "fleetscope-apply":         	            	FatalError{Underlying: error while running command: exit status 1; 
Step #8 - "fleetscope-apply":         	            	Error: Error waiting to create Feature: Error waiting for Creating Feature: Error code 13, message: an internal error has occurred
Step #8 - "fleetscope-apply":         	            	
Step #8 - "fleetscope-apply":         	            	  with module.env.google_gke_hub_feature.mcs,
Step #8 - "fleetscope-apply":         	            	  on ../../modules/env_baseline/mcg.tf line 34, in resource "google_gke_hub_feature" "mcs":
Step #8 - "fleetscope-apply":         	            	  34: resource "google_gke_hub_feature" "mcs" {
Step #8 - "fleetscope-apply":         	            	}
Step #8 - "fleetscope-apply":         	Test:       	TestFleetscope/non-production
```

**Comment by apeabody** [comment]
```
        	Error:      	Received unexpected error:
        	            	FatalError{Underlying: error while running command: exit status 1; 
        	            	Error: Error waiting to create Feature: Error waiting for Creating Feature: Error code 13, message: an internal error has occurred
        	            	
        	            	  with module.env.google_gke_hub_feature.mcs,
        	            	  on ../../modules/env_baseline/mcg.tf line 34, in resource "google_gke_hub_feature" "mcs":
        	            	  34: resource "google_gke_hub_feature" "mcs" {
        	            	}
        	Test:       	TestFleetscope/production
```

**Comment by apeabody** [comment]
```
        	Error:      	Received unexpected error:
        	            	FatalError{Underlying: error while running command: exit status 1; 
        	            	Error: Error waiting to create Feature: Error waiting for Creating Feature: Error code 13, message: an internal error has occurred
        	            	
        	            	  with module.env.google_gke_hub_feature.poco_feature,
        	            	  on ../../modules/env_baseline/policy.tf line 17, in resource "google_gke_hub_feature" "poco_feature":
        	            	  17: resource "google_gke_hub_feature" "poco_feature" {
        	            	}
        	Test:       	TestFleetscope/non-production
```

```
        	Error:      	Received unexpected error:
        	            	FatalError{Underlying: error while running command: exit status 1; 
        	            	Error: Error waiting to create Feature: Error waiting for Creating Feature: Error code 13, message: an internal error has occurred
        	            	
        	            	  with module.env.google_gke_hub_feature.acm_feature,
        	            	  on ../../modules/env_baseline/acm.tf line 44, in resource "google_gke_hub_feature" "acm_feature":
        	            	  44: resource "google_gke_hub_feature" "acm_feature" {
        	            	}
        	Test:       	TestFleetscope/production
```

**Comment by apeabody** [comment]
```
        	Error:      	Received unexpected error:
        	            	FatalError{Underlying: error while running command: exit status 1; 
        	            	Error: Error waiting to create Feature: Error waiting for Creating Feature: Error code 13, message: an internal error has occurred
        	            	
        	            	  with module.env.google_gke_hub_feature.mcs,
        	            	  on ../../modules/env_baseline/mcg.tf line 34, in resource "google_gke_hub_feature" "mcs":
        	            	  34: resource "google_gke_hub_feature" "mcs" {
        	            	}
        	Test:       	TestFleetscope/production
```

**Comment by apeabody** [comment]
```
TestFleetscope/development 2024-07-12T15:40:12Z retry.go:144: 'terraform [apply -input=false -auto-approve -var cluster_project_id=eab-gke-development-69xp -var network_project_id=eab-vpc-development-lg6y -var fleet_project_id=eab-gke-development-69xp -var cluster_membership_ids=["//gkehub.googleapis.com/projects/eab-gke-development-69xp/locations/us-central1/memberships/cluster-us-central1-development"] -var namespace_ids={"transactions" = "transactions-b4ls6q@test.blueprints.joonix.net", "accounts" = "accounts-b4ls6q@test.blueprints.joonix.net", "frontend" = "frontend-b4ls6q@test.blueprints.joonix.net"} -no-color -lock=false --parallelism=1]' failed with the error 'error while running command: exit status 1; 
Error: Provider produced inconsistent result after apply

When applying changes to module.env.google_sourcerepo_repository.acm_repo,
provider "provider[\"registry.terraform.io/hashicorp/google\"]" produced an
unexpected new value: Root object was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.' but this error was expected and warrants a retry. Further details: Provider eventual consistency error.

TestFleetscope/development 2024-07-12T15:40:12Z retry.go:103: terraform [apply -input=false -auto-approve -var cluster_project_id=eab-gke-development-69xp -var network_project_id=eab-vpc-development-lg6y -var fleet_project_id=eab-gke-development-69xp -var cluster_membership_ids=["//gkehub.googleapis.com/projects/eab-gke-development-69xp/locations/us-central1/memberships/cluster-us-central1-development"] -var namespace_ids={"transactions" = "transactions-b4ls6q@test.blueprints.joonix.net", "accounts" = "accounts-b4ls6q@test.blueprints.joonix.net", "frontend" = "frontend-b4ls6q@test.blueprints.joonix.net"} -no-color -lock=false --parallelism=1] returned an error: error while running command: exit status 1; 
Error: Provider produced inconsistent result after apply

When applying changes to module.env.google_sourcerepo_repository.acm_repo,
provider "provider[\"registry.terraform.io/hashicorp/google\"]" produced an
unexpected new value: Root object was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.. Sleeping for 2m0s and will try again.
```

**Review by gtsorbo — APPROVED** [review]
LGTM, thanks so much!

**Pull request merged**
