### PR TITLE
feat: added virtual service and destination rule to allow for localit…

### PR DESCRIPTION
**Pull request by yliaog**
…y load balancing

### CODE REVIEW

**Review by apeabody — DISMISSED** [review]
I recommend we wait till after https://github.com/GoogleCloudPlatform/terraform-google-enterprise-application/pull/55 is merged for test coverage.

**Comment by apeabody** [comment]
Something strange going on the with the SA in the CI, doing some exploration: https://github.com/GoogleCloudPlatform/terraform-google-enterprise-application/pull/66

**Review by gtsorbo — APPROVED** [review]

**Comment by apeabody** [comment]
```
Step #15 - "appinfra-verify": TestAppinfraFrontend 2024-04-22T19:57:53Z command.go:100: Running command gcloud with args [deploy rollouts list --project=app1-admin-5799 --delivery-pipeline=frontend --region=us-central1 --release=projects/app1-admin-5799/locations/us-central1/deliveryPipelines/frontend/releases/frontend-3d6ce15-20240422-1925 --filter targetId=frontend-dev --format json]
Step #15 - "appinfra-verify": TestAppinfraFrontend 2024-04-22T19:57:54Z command.go:185: [
Step #15 - "appinfra-verify": TestAppinfraFrontend 2024-04-22T19:57:54Z command.go:185:   {
Step #15 - "appinfra-verify": TestAppinfraFrontend 2024-04-22T19:57:54Z command.go:185:     "approvalState": "DOES_NOT_NEED_APPROVAL",
Step #15 - "appinfra-verify": TestAppinfraFrontend 2024-04-22T19:57:54Z command.go:185:     "createTime": "2024-04-22T19:25:47.901044Z",
Step #15 - "appinfra-verify": TestAppinfraFrontend 2024-04-22T19:57:54Z command.go:185:     "deployEndTime": "2024-04-22T19:26:35.429408150Z",
Step #15 - "appinfra-verify": TestAppinfraFrontend 2024-04-22T19:57:54Z command.go:185:     "deployFailureCause": "EXECUTION_FAILED",
Step #15 - "appinfra-verify": TestAppinfraFrontend 2024-04-22T19:57:54Z command.go:185:     "deployStartTime": "2024-04-22T19:26:08.381687639Z",
Step #15 - "appinfra-verify": TestAppinfraFrontend 2024-04-22T19:57:54Z command.go:185:     "deployingBuild": "projects/259716316813/locations/us-central1/builds/4be4cca7-9355-4383-8156-bf419ffb4506",
Step #15 - "appinfra-verify": TestAppinfraFrontend 2024-04-22T19:57:54Z command.go:185:     "enqueueTime": "2024-04-22T19:26:03.664077Z",
Step #15 - "appinfra-verify": TestAppinfraFrontend 2024-04-22T19:57:54Z command.go:185:     "etag": "912cea9a9850f4ad",
Step #15 - "appinfra-verify": TestAppinfraFrontend 2024-04-22T19:57:54Z command.go:185:     "name": "projects/app1-admin-5799/locations/us-central1/deliveryPipelines/frontend/releases/frontend-3d6ce15-20240422-1925/rollouts/frontend-3d6ce15-20240422-1925-to-frontend-dev-0001",
Step #15 - "appinfra-verify": TestAppinfraFrontend 2024-04-22T19:57:54Z command.go:185:     "phases": [
Step #15 - "appinfra-verify": TestAppinfraFrontend 2024-04-22T19:57:54Z command.go:185:       {
Step #15 - "appinfra-verify": TestAppinfraFrontend 2024-04-22T19:57:54Z command.go:185:         "deploymentJobs": {
Step #15 - "appinfra-verify": TestAppinfraFrontend 2024-04-22T19:57:54Z command.go:185:           "deployJob": {
Step #15 - "appinfra-verify": TestAppinfraFrontend 2024-04-22T19:57:54Z command.go:185:             "deployJob": {},
Step #15 - "appinfra-verify": TestAppinfraFrontend 2024-04-22T19:57:54Z command.go:185:             "id": "deploy",
Step #15 - "appinfra-verify": TestAppinfraFrontend 2024-04-22T19:57:54Z command.go:185:             "jobRun": "projects/259716316813/locations/us-central1/deliveryPipelines/frontend/releases/frontend-3d6ce15-20240422-1925/rollouts/frontend-3d6ce15-20240422-1925-to-frontend-dev-0001/jobRuns/f993ce8d-3ea8-4258-b345-7e7c3a108686",
Step #15 - "appinfra-verify": TestAppinfraFrontend 2024-04-22T19:57:54Z command.go:185:             "state": "FAILED"
Step #15 - "appinfra-verify": TestAppinfraFrontend 2024-04-22T19:57:54Z command.go:185:           },
Step #15 - "appinfra-verify": TestAppinfraFrontend 2024-04-22T19:57:54Z command.go:185:           "verifyJob": {
Step #15 - "appinfra-verify": TestAppinfraFrontend 2024-04-22T19:57:54Z command.go:185:             "id": "verify",
Step #15 - "appinfra-verify": TestAppinfraFrontend 2024-04-22T19:57:54Z command.go:185:             "state": "DISABLED",
Step #15 - "appinfra-verify": TestAppinfraFrontend 2024-04-22T19:57:54Z command.go:185:             "verifyJob": {}
Step #15 - "appinfra-verify": TestAppinfraFrontend 2024-04-22T19:57:54Z command.go:185:           }
Step #15 - "appinfra-verify": TestAppinfraFrontend 2024-04-22T19:57:54Z command.go:185:         },
Step #15 - "appinfra-verify": TestAppinfraFrontend 2024-04-22T19:57:54Z command.go:185:         "id": "stable",
Step #15 - "appinfra-verify": TestAppinfraFrontend 2024-04-22T19:57:54Z command.go:185:         "state": "FAILED"
Step #15 - "appinfra-verify": TestAppinfraFrontend 2024-04-22T19:57:54Z command.go:185:       }
Step #15 - "appinfra-verify": TestAppinfraFrontend 2024-04-22T19:57:54Z command.go:185:     ],
Step #15 - "appinfra-verify": TestAppinfraFrontend 2024-04-22T19:57:54Z command.go:185:     "state": "FAILED",
Step #15 - "appinfra-verify": TestAppinfraFrontend 2024-04-22T19:57:54Z command.go:185:     "targetId": "frontend-dev",
Step #15 - "appinfra-verify": TestAppinfraFrontend 2024-04-22T19:57:54Z command.go:185:     "uid": "ed01c07c459e4aa399911224277ab5d5"
Step #15 - "appinfra-verify": TestAppinfraFrontend 2024-04-22T19:57:54Z command.go:185:   }
Step #15 - "appinfra-verify": TestAppinfraFrontend 2024-04-22T19:57:54Z command.go:185: ]
Step #15 - "appinfra-verify":     poll.go:31: failed to pull provided condition after 30 retries, last error: polling timed out after 30 retries with 60.00 second intervals
```

**Comment by yliaog** [comment]
2024-04-22 12:26:34.878 PDT
 - stderr: "resource mapping not found for name: \"frontend\" namespace: \"\" from \"/workspace/stable/manifest.yaml\": no matches for kind \"DestinationRule\" in version \"networking.istio.io/v1beta1\"\nensure CRDs are installed first\nresource mapping not found for name: \"frontend\" namespace: \"\" from \"/workspace/stable/manifest.yaml\": no matches for kind \"VirtualService\" in version \"networking.istio.io/v1beta1\"\nensure CRDs are installed first\n"

**Comment by apeabody** [comment]
> Found the cause from https://pantheon.corp.google.com/deploy/delivery-pipelines/us-central1/frontend/releases/frontend-3d6ce15-20240422-1925/rollouts/frontend-3d6ce15-20240422-1925-to-frontend-dev-0001;row=job:stable:deploy?e=13802955&project=app1-admin-5799
> 
> 2024-04-22 12:26:34.878 PDT
> 
> * stderr: "resource mapping not found for name: "frontend" namespace: "" from "/workspace/stable/manifest.yaml": no matches for kind "DestinationRule" in version "networking.istio.io/v1beta1"\nensure CRDs are installed first\nresource mapping not found for name: "frontend" namespace: "" from "/workspace/stable/manifest.yaml": no matches for kind "VirtualService" in version "networking.istio.io/v1beta1"\nensure CRDs are installed first\n"

@yliaog  We can enable Istio with `istio = true` added to https://github.com/GoogleCloudPlatform/terraform-google-enterprise-application/blob/main/2-multitenant/modules/env_baseline/main.tf#L108

**Comment by apeabody** [comment]
> > Found the cause from https://pantheon.corp.google.com/deploy/delivery-pipelines/us-central1/frontend/releases/frontend-3d6ce15-20240422-1925/rollouts/frontend-3d6ce15-20240422-1925-to-frontend-dev-0001;row=job:stable:deploy?e=13802955&project=app1-admin-5799
> > 2024-04-22 12:26:34.878 PDT
> > 
> > * stderr: "resource mapping not found for name: "frontend" namespace: "" from "/workspace/stable/manifest.yaml": no matches for kind "DestinationRule" in version "networking.istio.io/v1beta1"\nensure CRDs are installed first\nresource mapping not found for name: "frontend" namespace: "" from "/workspace/stable/manifest.yaml": no matches for kind "VirtualService" in version "networking.istio.io/v1beta1"\nensure CRDs are installed first\n"
> 
> @yliaog We can enable Istio on the GKE clusters with `istio = true` added to https://github.com/GoogleCloudPlatform/terraform-google-enterprise-application/blob/main/2-multitenant/modules/env_baseline/main.tf#L108. However I don't believe that's our end intention.

Could we use `HTTPRoute` instead of `VirtualService`?

```
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
```

**Comment by yliaog** [comment]
it turns out https://github.com/GoogleCloudPlatform/terraform-google-enterprise-application/pull/66 does not work, that PR granted mesh config service account the service mesh agent role, but did not grant the mesh service account (in the form of @gcp-sa-servicemesh.iam.gserviceaccount.com) the role. As a result, service mesh failed to be provisioned in the cluster. and hence, the destinationrule  etc CRDs are missing, which caused the CI failure.

**Comment by yliaog** [comment]
It seems to be a race, the API is enabled, but probably not ready at the time appinfra-apply was run

$ gcloud services list --project app1-admin-2946 |grep deploy
clouddeploy.googleapis.com             Cloud Deploy API

https://ff13b16f16580d2debc7c1307cf973b868e0d009571f8e6e229c18b-apidata.googleusercontent.com/download/storage/v1/b/2843445864.cloudbuild-logs.googleusercontent.com/o/log-6444dc19-4945-4ed6-8637-6cb52766806a.txt?jk=AWNiL9Jntc1ZXrWNONZoEJmeewaxmdO8VtiTtPKWXDkRjfaQ8ZYhZH--UcsTToik3ZPbirIDXRk8IzdJ0AqNh4GjA5qdX4072MvYq7TrM-B3o3OLjZGP4T4Fz7oTsJEFs8FJa_97H1MoiL0o0XDe2giKeq_egGa_4BVIeNQp923sBWNRxSB0WyWqZGa4upxB5YKrvatXggd99o_UW_ogJlJ-hhHeFIUVGL0CBNATptr2dxvoWFXURxR1VAfTdYkD9VXCwQUWae7sxtrYRNCOLXos6uVjRkpkdq6TdU64dnoFH4Bv51QcCM14VGhUGZUEonhHql4-fh36TBWMl_2mxiq26onkzKfVlZrSIpfA3f6MPx6agh9kVPdJZjQ44gsFs30u-FYnou9mm6CgsI3uFDOLN2PSj2iEi0CEm-dPrFeF8waFai4H0mUaCXi_95M5RYHYim6Aslg4rUTh1Fdv3R1-TqlJFNcYEQxKVQp9hbhQYQdi9M-hnpuE5Nk1VVsQlOuUJTL8OezaOSFgQcDZXiseXbbwq9sE0PddovG6rwKXrJZ7f_f9v0t_jV8G-OyqewfjSbVb43cePE98Yog7gIXZLwrIAIVbqN9lYR-SwwssQ8tMkyJPwLXzGdjVMshXhYXAUtl9t-TPxlpK92GkEAizLXP99GRDZeFpkxb5bI1PxwHm2QVp_RGxFOzTFwyW3xDiZaqmsH9rcTHb0tVS1jlBlVBIJ5ZMaFh86hmZXftbEyegk1K8nY3lYLtLlDnmGjlwLYsTiVSwI8b2IygNtDuBYGxd-ONyhoC8nKCNl9ZobY0tRZjFJg-qljkqMrAYvBc8jYQLxOSFGEa8JkERd_7SBNZ91uDZoQicjpWUgJ3t9d13gfUqyAly8qjpkbVb8osuN-BmRly-AJxdmThYr2LTnJlZr7jRlmKlQPw1zEUnuQlw4nPMKT-V8cljRoq79Re9yuN7ScVunB1gWXFDHvhGIGJ8bPqWNSi2cJy5RYmVRyoiNzZfq18OIQLqTkTIe75LVHq1Bnb65Jner57dnCYv32f1qHRuYENcNb_oyhcz8vbaMOei2Kn_MlBaXXqSADekG4MLL4s-HCwpBhxhkAUgHSw-1XDDO8AbOjlxgBgZPMXSxrMzINN0nGDSg8FF2T-PN-XiaUSAwwN6Gk1IYFyZ6qF55t0daBUDgoy5_QPpTBheoM187DRiUt9atmLDwCr7sTh7harVnQ5wF5UW1foRuLdziLXJxRP1bscUVd8wntxToYhon8wMgIksSDCGjfH-vkHS2vU_&isca=1
Step #14 - "appinfra-apply": TestAppinfraFrontend 2024-04-23T03:55:01Z command.go:185: Error: Error creating Target: googleapi: Error 403: Cloud Deploy API has not been used in project app1-admin-2946 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/clouddeploy.googleapis.com/overview?project=app1-admin-2946 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.

**Comment by apeabody** [comment]
> it turns out #66 does not work, that PR granted mesh config service account the service mesh agent role, but did not grant the mesh service account (in the form of @gcp-sa-servicemesh.iam.gserviceaccount.com) the role. As a result, service mesh failed to be provisioned in the cluster. and hence, the destinationrule etc CRDs are missing, which caused the CI failure.

@yliaog - Are you saying that `google_project_service_identity.fleet_meshconfig_sa.email` is returning the wrong value?  Per the doc it should the desired: `service-PROJECT_NUMBER@gcp-sa-servicemesh.iam.gserviceaccount.com`


```https://cloud.google.com/iam/docs/service-agents
Anthos Service Mesh Service Account
Service agent for meshconfig.googleapis.com.
service-PROJECT_NUMBER@gcp-sa-servicemesh.iam.gserviceaccount.com
```

**Comment by yliaog** [comment]
i confirmed by running the TF locally last night,

google_project_service_identity.fleet_meshconfig_sa.email returns
serviceAccount:service-131241285558@gcp-sa-meshconfig.iam.gserviceaccount.com, instead of service-PROJECT_NUMBER@gcp-sa-servicemesh.iam.gserviceaccount.com

**Comment by apeabody** [comment]
> i confirmed by running the TF locally last night,
> 
> google_project_service_identity.fleet_meshconfig_sa.email returns serviceAccount:[service-131241285558@gcp-sa-meshconfig.iam.gserviceaccount.com](mailto:service-131241285558@gcp-sa-meshconfig.iam.gserviceaccount.com), instead of [service-PROJECT_NUMBER@gcp-sa-servicemesh.iam.gserviceaccount.com](mailto:service-PROJECT_NUMBER@gcp-sa-servicemesh.iam.gserviceaccount.com)

Thanks! I'll follow-up with you directly. :)

**Review by apeabody — APPROVED** [review]

**Review by apeabody — APPROVED** [review]
Thanks @yliaog!

LGTM / @gtsorbo has already approved

**Pull request merged**
