### PR TITLE
fix: migrate non-production to nonproduction

### PR DESCRIPTION
**Pull request by apeabody**
Fixes: https://github.com/GoogleCloudPlatform/terraform-google-enterprise-application/issues/178

### CODE REVIEW

**Review by yliaog — APPROVED** [review]
do we need to change file names also?

**Comment by apeabody** [comment]
> do we need to change file names also?

I thought I caught all the directory names (didn't see an filenames), but if I missed any let me know.

**Comment by yliaog** [comment]
aah, ok. then we should be good.

**Review by gtsorbo — APPROVED** [review]
LGTM!

**Pull request merged**
