### PR TITLE
feat: adds frontend app infra test

### PR DESCRIPTION
**Pull request by amandakarina**
Adds infra test for frontend application

### CODE REVIEW

**Comment by amandakarina** [comment]
> ```
> Step #15 - "appinfra-verify": TestAppinfraFrontend 2024-05-08T20:37:29Z command.go:185: fatal: unable to access 'https://source.developers.google.com/p/eab-cymbal-bank-frontend/r/frontend-admin-62cd/': The requested URL returned error: 403
> Step #15 - "appinfra-verify":     frontend_test.go:230: error while running command: exit status 128; remote: PERMISSION_DENIED: The caller does not have permission
> Step #15 - "appinfra-verify":         remote: [type.googleapis.com/google.rpc.RequestInfo]
> Step #15 - "appinfra-verify":         remote: request_id: "e055cc33af7c4d0d920541578d5bd422"
> Step #15 - "appinfra-verify":         fatal: unable to access 'https://source.developers.google.com/p/eab-cymbal-bank-frontend/r/frontend-admin-62cd/': The requested URL returned error: 403
> ```

fixed!

**Review by gtsorbo — APPROVED** [review]

**Comment by amandakarina** [comment]
> /gcbrun

@apeabody could you, please, trigger again?

**Comment by amandakarina** [comment]
> /gcbrun

@apeabody could, you, please, trigger again?

**Comment by apeabody** [comment]
Looks like a race condition in fleetscope

```
Error: Error creating Feature: googleapi: Error 409: Resource 'projects/eab-gke-production-63aq/locations/global/features/multiclusterservicediscovery' already exists
Details:
[
  {
    "@type": "type.googleapis.com/google.rpc.ResourceInfo",
    "resourceName": "projects/eab-gke-production-63aq/locations/global/features/multiclusterservicediscovery"
  }
]

  with module.env.google_gke_hub_feature.mcs,
  on ../../modules/env_baseline/mcg.tf line 32, in resource "google_gke_hub_feature" "mcs":
  32: resource "google_gke_hub_feature" "mcs" {
  ```
  
  re-triggering

**Pull request merged**
